@startuml
(*) --> [开始] "用户充值请求"

if "请求数据校验" then
note left
* 账户状态
* 充值金额
* 重复充值
* ...
end note
if "加锁"  then
note left
* 防止重复提交
end note
--> 加锁成功
--> 创建充值交易
note left
* 充提转 的统一入口
* 着重记录用户未完结的支付信息
end note

partition 开启事务A{
--> "记录充值记录表 (pending 状态)"
--> 更新充值交易状态
--> "生成预支付单号/QR-Code"
}
--> "释放锁"
--> "用户充值" as dp

partition 获取支付结果{
if "" then
--> [支付结果通知] 支付结果通知
--> ====b2====
else
--> [超时未获取到支付结果] "调用银行接口\n查询支付状态"
--> ====b2====
endif
}

partition "开启事务B"{
--> 更新交易状态
--> 更新提现记录表
}



-->(*)
else
-->[加锁失败] "流程终止"
'-->(*)
endif


'--> [true] "落库交易表"
'
'
'--> [true] "更新交易状态"
'--> [true] "更新账户余额"
'--> [true] "记录充值记录"
'--> [true] "解锁交易"
'--> [true] "发送支付结果通知"
'--> [true] "返回支付结果"





else
-right->[false] "流程终止"
-right-> (*)
endif



@enduml