@startuml
(*) --> [开始] "用户提现请求"

if "请求数据校验" then
note left
* 账户状态
* 提现金额
* 重复提现(防止重复提交)
* ...
end note
if "加锁"  then
--> 加锁成功
--> 创建提现交易
note left
* 充提转 的统一入口
* 着重记录用户未完结(余额扣减类单子)
end note

--> "记录提现记录表 (pending 状态)"

partition 开启事务A{
--> 调用银行接口转账
--> 更新提现记录表状态
--> 更新交易表状态
}

partition 获取转账结果{
if "" then
--> [转账结果回调] ====b2====
else
--> [超时未获取到支付结果] "调用银行接口\n查询支付状态"
--> ====b2====
endif
}
--> 获取到转账结果

partition "开启事务B"{
--> 更新交易状态
--> 更新转账记录表
}
--> 释放锁


-->(*)
else
-->[加锁失败] "流程终止"
endif


else
-right->[false] "流程终止"
-right-> (*)
endif
@enduml