@startuml
(*) --> [开始] "用户转账请求"

if "数据校验" then
note left
* 账户状态
* 转账金额
* 重复充值
* ...
end note
if "加锁"  then
note left
* 防止重复提交
end note
--> 加锁成功
--> 创建转账交易
note left
* 充提转 的统一入口
* 转账金额预扣减(锁单)
   防止同时存在多个未完成转账单,导致转账金额超限
end note

--> "落库 转账记录表 (pending 状态)"
partition 开启事务A{
--> 扣减用户A余额
--> 增加用户B余额
--> 更新转账记录表状态
--> 更新转账交易表状态
--> =====b1=====
}


--> 释放锁


-->(*)
else
-->[加锁失败] "流程终止"
endif


else
-right->[false] "流程终止"
-right-> (*)
endif


@enduml